name: helloworld

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: helloworld
        run: echo "hello world"
