name: helloworld

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: helloworld
        run: echo "hello world"

      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hello World
